### ISSUE TITLE
Does not make tailwindcss binary executable

### ISSUE THREAD

**Issue by paulvt** [wingertge/perseus-tailwind#1]
Hi! Thanks for the plugin. I was trying it out, but couldn't get it to work at first:

```
Error: plugin 'tailwind-plugin' returned an error (this is unlikely to be Perseus' fault)

Caused by:
	Failed to run Tailwind CLI
```

It turns out that the cause is that the `tailwindcss-linux-x64` binary was not made executable after downloading it.

**Comment by wingertge** [comment]
I tried making it executable with this code, but I'm not  super familiar with Linux so it might be wrong. Would 555 be the right permission instead?
```rust
    #[cfg(target_family = "unix")]
    {
        println!("Making the binary executable...");
        use std::os::unix::fs::PermissionsExt;
        let mut perms = file
            .metadata()
            .map_err(|_| "Failed to get metadata for binary to set executable permission")?
            .permissions();
        let mode = perms.mode() | 0o550;
        perms.set_mode(mode);
    }
```

**Comment by paulvt** [comment]
Yes!

**Comment by wingertge** [comment]
It should be fixed in the GitHub version now, if you have time it would be great to know if it works now.

**Comment by paulvt** [comment]
Unfortunately, it did not change anything?

**Comment by wingertge** [comment]
I know it's the most annoying statement ever, but it works on my machine (WSL) and I don't know how to further debug things without being able to reproduce the problem. I'll push a new version with the permissions you suggested and hopefully that'll fix it for most people.
