### ISSUE TITLE
Example setup leads to failed export

### ISSUE THREAD

**Issue by paulvt** [wingertge/perseus-tailwind#2]
I have setup the plugin as suggested in the [source code](https://github.com/wingertge/perseus-tailwind/blob/7c654581fce33db0efbc6a21ea6844f878095b81/src/lib.rs#L15-L21). This works great using `perseus serve`, but not with `perseus export` for some reason:

```
Error: couldn't copy static alias file from 'dist/static/tailwind.css' to './dist/exported/static/tailwind.css'

Caused by:
	No such file or directory (os error 2)
```

Or is this a bug in perseus 0.4? I am currently using perseus 0.4.0-beta.19.

(Note that the documentation in the README is different and seems to refer more to a perseus 0.3 situation? Maybe this should be updated?)

**Comment by wingertge** [comment]
This is a problem with perseus as far as I can tell. Static aliases seem to get copied to the exported folder before the `before_export` plugin action is run. If you look at the dist directory for the failed export the `tailwind.css` file should be there, but it was written there after the copy step.

Thanks for alerting me to the outdated example in the README though.

**Comment by wingertge** [comment]
I managed to figure out the issue, and it is actually a bug in perseus (though there was another bugfix I just pushed out).
Right now any static alias that starts with `/static/` breaks on export. If you just put it at `/tailwind.css` or something like that it should work.
