### ISSUE TITLE
in_file overrides automatic file detection

### ISSUE THREAD

**Issue by nashley** [wingertge/perseus-tailwind#4]
The config in [tailwind.config.js](https://github.com/wingertge/perseus-tailwind/blob/master/src/default-config.js) automatically parses project files, but the [in_file parameter overrides this](https://github.com/wingertge/perseus-tailwind/blob/master/src/lib.rs#L115) and doesn't seem to be especially useful.

Is there a reason why this parameter shouldn't just be removed or at least made optional?

**Comment by wingertge** [comment]
There's zero real documentation for the CLI on the Tailwind site, and the example uses the in file.  So I kind of assumed it was mandatory. I just pushed a new version that makes it optional and also allows custom config file paths. The options struct now exposes a builder pattern to make it more ergonomic with the optional parameters.
